//choices of words
export.word = {
	list:['GERMAN SHEPHERD', 'LABRADOR RETRIEVER', 'ROTTWEILER', 'BEAGLE', 'BULLDOG', 'GOLDEN RETRIEVER', 'GREAT DANE', 'POODLE', 'DOBERMANN', 'DACHSHUND', 'SIBERIAN HUSKY', 'CHIHUAHUA', 'ENGLISH MASTIFF', 'BOXER', 'PUG', 'CHOW CHOW', 'BODER COLLIE', 'VIZSLA', 'YORKSHIRE TERRIER', 'SHIH TZU', 'PIT BULL', 'AUSTRALIAN SHEPHERD', 'MALTESE DOG', 'GREYHOUND'],
};